---

- name: Install haproxy
  sudo: true
  apt: name=haproxy state=present

- name: haproxy service state
  sudo: true
  service: name=haproxy state=started

- name: Configure haproxy
  sudo: true
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy
